# Generated by Django 5.1.5 on 2025-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('move', models.CharField(max_length=50)),
                ('loss', models.TextField()),
                ('best_mode', models.CharField(max_length=50)),
                ('classification', models.TextField()),
                ('opening_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
