# Generated by Django 5.1.5 on 2025-02-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moveanalysis',
            old_name='best_mode',
            new_name='best_move',
        ),
    ]
