# Generated by Django 5.1.5 on 2025-02-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_rename_best_mode_moveanalysis_best_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveanalysis',
            name='loss',
            field=models.FloatField(),
        ),
    ]
